data:
  data_location: ../drive/MyDrive/audio_ddsp
  extension: "wav"

preprocess:
  sampling_rate: &samplingrate 16000
  signal_length: &signallength 64000
  block_size: &blocksize 256 # must be a power of 2 if using realtime

  oneshot: false # crop every audio file to exactly signal length
  out_dir: ../drive/MyDrive/preprocessed

model:
  hidden_size: &hidden_size 512
  sampling_rate: *samplingrate
  block_size: *blocksize

train:
  scales: [2048, 1024, 512, 256, 128, 64]
  overlap: [0.75, 0.75, 0.75, 0.75, 0.75, 0.75]
